version: '3.7'

services:

  urls-db:
    image: inaciowilson/urls-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - shortener-net
    deploy:
      placement:
        constraints:
          - 'node.role == worker'
  
  urls-cache:
    image: redis
    ports:
      - 6379:6379
    networks:
      - shortener-net
    deploy:
      placement:
        constraints:
          - 'node.role == worker'
          
  urls-redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - shortener-net
    deploy:
      placement:
        constraints:
          - 'node.role == worker'
  
  urls-api:
    image: inaciowilson/urls-api
    ports:
      - "8080:8080"
    networks:
      - shortener-net
    deploy:
      replicas: 3
      placement:
        constraints:
          - 'node.role == worker'
    depends_on:
      - urls-db
      - urls-cache

networks:
  shortener-net: